# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Evaluate exam specific likelihood
#'
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param DAY Day of interest.
#' @param MAX_DAY Last day of observation.
#' @param OBSFLAG TRUE for observed, FALSE for not-observed.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of observing or not a specific
#' grade on a given exam before a given day conditioned on ability and speed.
#'
#' @export
examLik <- function(EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, LOGFLAG = FALSE) {
    .Call(`_crirt_examLik`, EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, LOGFLAG)
}

#' Evaluate the gradient of exam-specific log-likelihood
#'
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param DAY Day of interest.
#' @param MAX_DAY Last day of observation.
#' @param OBSFLAG TRUE for observed, FALSE for not-observed.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param ROTATED Have the latent scores been rotated using their covariance matrix?
#'
#' @returns It returns the probability of observing or not a specific
#' grade on a given exam before a given day conditioned on ability and speed.
#'
#' @export
grl_examLik <- function(EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, ROTATED) {
    .Call(`_crirt_grl_examLik`, EXAM, GRADE, DAY, MAX_DAY, OBSFLAG, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, SPEED, ROTATED)
}

#' Extract indices of parameters related to the IRT model
#'
#' `THETA_IRT` is assumed to be ordered as follows
#' c(exam1_int, exam1_slope, exam1_time_loc, exam1, time_sca, exam2_int, ...)
#'
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `0:(N_EXAMS-1)`.
#'
#' @returns It return a vector with two values representing the starting
#' index and the length of the segment of THETA_IRT corresponding to
#' the parameter of interest.
#'
#' @export
extract_params_idx_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_idx_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Extract parameters related to the IRT model
#'
#' See [extract_params_idx_irt]
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `1:N_EXAMS`.
#' @export
extract_params_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Evaluate the probability of grades greater or equal than the reference one
#'
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining grades higher than `GRADE` on exam `EXAM`.
#'
#' @export
pGreaterGrades <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_crirt_pGreaterGrades`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the gradient of the probability of grades greater or equal than the reference one
#'
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#'
#' @returns It returns the gradient of the probability of obtaining grades higher than `GRADE` on exam `EXAM`.
#'
#' @export
gr_pGreaterGrades <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY) {
    .Call(`_crirt_gr_pGreaterGrades`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY)
}

#' Evaluate the probability of getting a specific grade
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining the grade `GRADE` on exam `EXAM`.
#' @export
pGrade <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_crirt_pGrade`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the gradient of the probability of getting a specific grade
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#'
#' @returns It returns the gradient of the probability of obtaining the grade `GRADE` on exam `EXAM`.
#' @export
gr_pGrade <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY) {
    .Call(`_crirt_gr_pGrade`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY)
}

#' Log-likelihood and gradient of the conditional GRTC Model on one observation
#'
#' Used for internal testing
#'
#' @param THETA Parameter vector
#' @param EXAMS_GRADES Vector of exam grades
#' @param EXAMS_DAYS Vector of Eexam days
#' @param EXAMS_SET Vector of binary values. 1 to include an exam in the study-plan, 0 otherwise
#' @param EXAMS_OBSFLAG Vector of binary values. 1 if the exam is observed, 0 otherwise
#' @param MAX_DAY Maximum day of observation
#' @param N_GRADES Number of possible grades modelled
#' @param N_EXAMS Number of possible exams modelled
#' @param ABILITY Ability latent parameter
#' @param SPEED Speed latent parameter
#' @param ROTATE TRUE to rotate latent scores using their covariance matrix
#' @param GRFLAG Set to true to return the gradient along the log-likelihood
#'
#' @export
conditional_igrtcm <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED, ROTATE, GRFLAG = TRUE) {
    .Call(`_crirt_conditional_igrtcm`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED, ROTATE, GRFLAG)
}

#' Log-likelihood and gradient of the complete GRTC Model on one observation
#'
#' Used for internal testing
#'
#' @param THETA Parameter vector
#' @param EXAMS_GRADES Vector of exam grades
#' @param EXAMS_DAYS Vector of exam days
#' @param EXAMS_SET Vector of binary values. 1 to include an exam in the study-plan, 0 otherwise
#' @param EXAMS_OBSFLAG Vector of binary values. 1 if the exam is observed, 0 otherwise
#' @param MAX_DAY Maximum day of observation
#' @param N_GRADES Number of possible grades modelled
#' @param N_EXAMS Number of possible exams modelled
#' @param ABILITY Ability latent parameter
#' @param SPEED Speed latent parameter
#'
#' @export
complete_igrtcm <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED) {
    .Call(`_crirt_complete_igrtcm`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, N_GRADES, N_EXAMS, ABILITY, SPEED)
}

#' Latent distribution
#'
#' Provides a wrapper for the cpp class `LAT_DISTR`, which computes
#' log density and gradient of the joint distribution of ability and speed.
#'
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param PARS Two elements, used as (`L[2,1]`, `L[2,2]`), where L is the lower triangular Cholesky of the latent covariance matrix.
#' @param GRFLAG `TRUE` to compute the gradient.
#'
#' @return It returns a list with:
#' \itemize{
#'   \item ll - The log-likelihood of the latent distribution.
#'   \item gr - The gradient of the log-likelihood.
#' }
#'
#' @export
internal_lat <- function(ABILITY, SPEED, PARS, GRFLAG = TRUE) {
    .Call(`_crirt_internal_lat`, ABILITY, SPEED, PARS, GRFLAG)
}

#' GRTCM computations with Gaussian quadrature
#'
#' Compute log-likelihood an gradient of the Graded response time-censored model
#'
#' @param THETA Parameter vector
#' @param EXAMS_GRADES Matrix of exam grades
#' @param EXAMS_DAYS Matrix of exam days
#' @param EXAMS_SET Matrix of binary values. 1 to include an exam in the study-plan, 0 otherwise
#' @param EXAMS_OBSFLAG Matrix of binary values. 1 if the exam is observed, 0 otherwise
#' @param MAX_DAY Vector with maximum day per observation
#' @param GRID Grid of quadrature points
#' @param WEIGHTS Weights of quadrature points
#' @param N_GRADES Number of possible grades modelled
#' @param N_EXAMS Number of possible exams modelled
#' @param ROTGRID TRUE to rotate the quadrature grid using the latent covariance matrix
#' @param GRFLAG Set to true to return the gradient along the log-likelihood
#'
#' @export
GRTCM_GH <- function(THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, GRID, WEIGHTS, N_GRADES, N_EXAMS, GRFLAG = TRUE, ROTGRID = TRUE) {
    .Call(`_crirt_GRTCM_GH`, THETA, EXAMS_GRADES, EXAMS_DAYS, EXAMS_SET, EXAMS_OBSFLAG, MAX_DAY, GRID, WEIGHTS, N_GRADES, N_EXAMS, GRFLAG, ROTGRID)
}

#' Intercepts reparameterisation
#'
#' @param X Intercepts or unconstrained parameter values for grades low-to-high.
#' @param CON2UN TRUE if going from the constrained space to the unconstrained one.
#'
#' @returns It allows to go back and forth from constrained intercepts
#' to unconstrained parameters.
#'
#' @export
reparThr <- function(X, CON2UN = FALSE) {
    .Call(`_crirt_reparThr`, X, CON2UN)
}

#' Evaluate the c.d.f or p.d.f of the last attempt to an exam
#'
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param DAY Day of interest.
#' @param THETA Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param SPEED speed value.
#' @param CDFFLAG `TRUE` for c.d.f. of time. `FALSE` for p.d.f.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @export
pTimeExam <- function(EXAM, DAY, THETA, N_GRADES, N_EXAMS, SPEED, CDFFLAG, LOGFLAG = FALSE) {
    .Call(`_crirt_pTimeExam`, EXAM, DAY, THETA, N_GRADES, N_EXAMS, SPEED, CDFFLAG, LOGFLAG)
}

#' Evaluate the gradient of the c.d.f or p.d.f of the last attempt to an exam
#'
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param DAY Day of interest.
#' @param THETA Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param SPEED speed value.
#' @param ABILITY ability value.
#' @param CDFFLAG `TRUE` for c.d.f. of time. `FALSE` for p.d.f.
#' @param ROTATED Have latent scores been rotated using their variance?
#' @param LOGFLAG TRUE to compute the gradient of the log density.(not available for cdf)
#'
#' @export
gr_pTimeExam <- function(EXAM, DAY, THETA, N_GRADES, N_EXAMS, SPEED, ABILITY, CDFFLAG, ROTATED, LOGFLAG = FALSE) {
    .Call(`_crirt_gr_pTimeExam`, EXAM, DAY, THETA, N_GRADES, N_EXAMS, SPEED, ABILITY, CDFFLAG, ROTATED, LOGFLAG)
}

