# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Extract indices of parameters related to the IRT model
#'
#' `THETA_IRT` is assumed to be ordered as follows
#' c(exam1_int, exam1_slope, exam1_time_loc, exam1, time_sca, exam2_int, ...)
#'
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `0:(N_EXAMS-1)`.
#'
#' @returns It return a vector with two values representing the starting
#' index and the length of the segment of THETA_IRT corresponding to
#' the parameter of interest.
#'
#' @export
extract_params_idx_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_idx_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Extract parameters related to the IRT model
#'
#' See [extract_params_idx_irt]
#' @param THETA_IRT parameter vector related to irt model
#' @param N_GRADES number of grades modelled.
#' @param N_EXAMS number of exams.
#' @param OPTION Select parameters of interest. `1` for exam-grades slopes,
#' `2` for exam-grade intercepts, `3` for time-location parameter,
#' `4` for time-scale parameter.
#' @param EXAM exam of interest. Possible values in `1:N_EXAMS`.
#' @export
extract_params_irt <- function(THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM) {
    .Call(`_crirt_extract_params_irt`, THETA_IRT, N_GRADES, N_EXAMS, OPTION, EXAM)
}

#' Evaluate the probability of grades greater or equal than the reference one
#'
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining grades higher than `GRADE` on exam `EXAM`.
#'
#' @export
pGreaterGrades <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_crirt_pGreaterGrades`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the gradient of the probability of grades greater or equal than the reference one
#'
#' @param GRADE Grade used as reference. Integers from 1 to N_GRADES.
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the gradient of the probability of obtaining grades higher than `GRADE` on exam `EXAM`.
#'
#' @export
gr_pGreaterGrades <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY) {
    .Call(`_crirt_gr_pGreaterGrades`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY)
}

#' Evaluate the probability of getting a specific grade
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the probability of obtaining the grade `GRADE` on exam `EXAM`.
#' @export
pGrade <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG = FALSE) {
    .Call(`_crirt_pGrade`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY, LOGFLAG)
}

#' Evaluate the gradient of the probability of getting a specific grade
#'
#' @param GRADE Grade used as reference
#' @param EXAM Exam of interest. Integers from 0 to N_EXAMS -1.
#' @param THETA_IRT Portion of the parameter vector related to the IRT model
#' @param N_GRADES Number of grades modelled.
#' @param N_EXAMS Number of exams.
#' @param ABILITY Ability value.
#' @param LOGFLAG Set TRUE to return log value.
#'
#' @returns It returns the gradient of the probability of obtaining the grade `GRADE` on exam `EXAM`.
#' @export
gr_pGrade <- function(GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY) {
    .Call(`_crirt_gr_pGrade`, GRADE, EXAM, THETA_IRT, N_GRADES, N_EXAMS, ABILITY)
}

#' Latent distribution
#'
#' Provides a wrapper for the cpp class `LAT_DISTR`, which computes
#' log density and gradient of the joint distribution of ability and speed.
#'
#' @param ABILITY ability value.
#' @param SPEED speed value.
#' @param PARS Two elements, used as (`L[2,1]`, `L[2,2]`), where L is the lower triangular Cholesky of the latent covariance matrix.
#' @param GRFLAG `TRUE` to compute the gradient.
#'
#' @return It returns a list with:
#' \itemize{
#'   \item ll - The log-likelihood of the latent distribution.
#'   \item gr - The gradient of the log-likelihood.
#' }
#'
#' @export
internal_lat <- function(ABILITY, SPEED, PARS, GRFLAG = TRUE) {
    .Call(`_crirt_internal_lat`, ABILITY, SPEED, PARS, GRFLAG)
}

#' Intercepts reparameterisation
#'
#' @param X Intercepts or unconstrained parameter values for grades low-to-high.
#' @param CON2UN TRUE if going from the constrained space to the unconstrained one.
#'
#' @returns It allows to go back and forth from constrained intercepts
#' to unconstrained parameters.
#'
#' @export
reparThr <- function(X, CON2UN = FALSE) {
    .Call(`_crirt_reparThr`, X, CON2UN)
}

